name: habit_garden
description: lame

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  blobs: ^1.2.0
  fluttertoast: ^7.1.6
  flutter_svg: ^0.19.2+1
  url_launcher: ^5.7.10
  provider: ^4.3.2+2
  get_it: ^5.0.3
  firebase_core: 0.5.3
  firebase_auth: ^0.18.4
  google_sign_in: ^4.5.1
  flutter_twitter_login: ^1.1.0
  flutter_facebook_auth: ^2.0.0
  cloud_firestore: ^0.14.4

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: assets/icon.png

flutter:

  uses-material-design: true

  assets:
    - assets/flowers/
    - assets/icons/
    - assets/titlebars/
    - assets/garden.svg
    - assets/cloud.svg
